spring:
    server:
        port: 8080
    datasource:
        url: jdbc:postgresql://localhost:5432/movie-service
        username: postgres
        password: mike123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
